# Generated by Django 3.2.6 on 2021-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messi_Ronaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.DateField(max_length=255, verbose_name='Season')),
                ('Player', models.CharField(max_length=255, verbose_name='Player')),
                ('Liga_Goals', models.IntegerField(verbose_name='Liga_Goals')),
                ('Liga_Asts', models.IntegerField(verbose_name='Liga_Asts')),
                ('Liga_Aps', models.IntegerField(verbose_name='Liga_Aps')),
                ('Liga_Mins', models.IntegerField(verbose_name='Liga_Mins')),
                ('Cl_Goals', models.IntegerField(verbose_name='CL_Goals')),
                ('Cl_Asts', models.IntegerField(verbose_name='CL_Asts')),
                ('Cl_Aps', models.IntegerField(verbose_name='CL_Aps')),
                ('Cl_Mins', models.IntegerField(verbose_name='CL_Mins')),
            ],
        ),
    ]
